version: '3'
services:
  app:
    container_name: planid
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
    environment: 
      - PATH_TO_DOCS=${PATH_TO_DOCS}
      - MONGODB_URI=${MONGODB_URI}
      - USERMAIL=${USERMAIL}
      - USERPASS=${USERPASS}
      - CHAVE_EXPRESS_SESSION=${CHAVE_EXPRESS_SESSION}
      - ENCRYPT_SECRET=${ENCRYPT_SECRET}
      - NODE_ENV=${NODE_ENV}
      - VIRTUAL_HOST=planid.ccmn.selfip.org
      - LETSENCRYPT_HOST=planid.ccmn.selfip.org
      - VIRTUAL_PORT=3000
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'