version: '3'
services:
  app:
    container_name: planid
    restart: always
    build: .
    ports:
      - '80:3000'
    external_links:
      - mongo
    environment: 
      - MONGODB_URI=mongodb://localhost:27017/planid-teste
      - USERMAIL=user@email.com
      - USERPASS=userPass
      - CHAVE_EXPRESS_SESSION=anyString
      - ENCRYPT_SECRET=anyString
      - NODE_ENV=development
      - VIRTUAL_HOST=planid.ccmn.selfip.org
      - LETSENCRYPT_HOST=planid.ccmn.selfip.org
      - VIRTUAL_PORT=3000
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'